version: '3.8'

services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    networks:
      - webnet
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  webnet:
    driver: bridge

volumes:
  dbdata:
